clean_patterns = [
    "([0-9])",
    "(\.)",
    "(\-)",
    "^(\s+)"
],

rejected = [
    "faq",
    "forum",
    "content",
    "recherche",
    "editorial",
    "solution",
    "paiement",
    "article",
    "annonce",
    "video",
    "config",
    "actualite",
    "lefigaro",
    "keljob",
    "journal",
    "magazine",
    "secure",
    "affich",
    "gratuit",
    "kiosque",
    "boutique",
    "ticketac",
    "marine",
    "viadeo",
    "glossary"
    "ville",
    "avis",
    "erreur",
    "glossary",
    "formation",
    "liste",
    "rayon",
    "moncomte",
    "media",
    "supprimer",
    "creer",
    "voir",
    "alerte",
    "france",
    "moncompte",
    "scan",
    "guide"
]

synonimous = {
    "management": "business",
    "ebusiness": "business",
    "gastronomie": "cuisine",
    "recette": "cuisine",
    "cuisiner": "cuisine",
    "dictionnaire": "langue",
    "conjugaison": "langue",
    "citation": "langue",
    "femme": "lifestyle",
    "mode": "lifestyle",
    "beaute": "lifestyle",
    "spectacle": "lifestyle",
    "sortir": "lifestyle",
    "bricolage": "maison",
    "chambre": "maison",
    "interieur": "maison",
    "jardin": "maison",
    "deco": "maison",
    "patrimoine": "finances",
    "argent": "finances",
    "maman": "quotidien",
    "maladie": "sante",
    "medecine": "sante",
    "football": "sport",
    "webtech": "hightech",
    "finance": "quotidien",
    "star": "people",
    "film": "cinema",
    "programme": "cinema",
    "droit": "finance",
    "download": "hightech",
    "television": "cinema",
    "telecharger": "hightech"
}
